
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:

 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * @author Aditya Majumdar
 *
 */
public class Euler2 {

	 public static void main(String []args){	        

	        int num1 = 1;
	        int num2 = 2;
	        
	        int sum = 2;
	        
	        outerloop:
	        for(int i = 0; i < 1000; i++)
	        {
	        	int temp = num2 + num1;
	        	num1 = num2;
	        	num2 = temp;
	        	if(num2 > 4000000)
	        	{
	        		break outerloop;
	        	}
	        	else
	        	{
	        		if(num2%2 == 0)
	        			sum+=num2;
	        	}
	        		
	        }
	        
	        
	        System.out.println("The result you want is " + sum);
	     }
	
}
